Update dropbox script, move to bin folder

diff --git a/bin/dropbox b/bin/dropbox
--- a/bin/dropbox
+++ b/bin/dropbox
@@ -2,17 +2,27 @@
 
 # For WSL, there are only a few things I care about on Dropbox.
 # Easiest just to hardcode them.
-declare -a paths=(
+declare -a remote_paths=(
 	"Coursework/5th Year - 2022-2023/Winter/COIS-4350H High Performance Computing"
-	# "Coursework/5th Year - 2022-2023/Winter/COIS-3320H Fundamentals of Operating Systems"
 )
+
+declare -a local_paths=(
+	"Coursework/COIS-4350H"
+)
+
+
+if [[ ! "${#local_paths[@]}" -eq "${#remote_paths[@]}" ]]
+then
+	>&2 echo "Invalid path configuration"
+	exit 1
+fi
 
 
 if [[ "$1" = "up" || "$1" = "down" ]]
 then
 	action="sync"
 	direction="$1"
-	shift
+	shift # shift so we can pass the rest directly to rclone
 elif [[ "$1" = "bisync" ]]
 then
 	action="bisync"
@@ -24,10 +34,10 @@ else
 fi
 
 
-for path in "${paths[@]}"
+for i in "${!local_paths[@]}"
 do
-	local_path="${HOME}/Dropbox/$path"
-	remote_path="dropbox:/$path"
+	local_path="${HOME}/${local_paths[i]}"
+	remote_path="dropbox:/${remote_paths[i]}"
 
 	if [[ "$direction" = "up" ]]
 	then
